---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: install yum-utils
      yum: name=yum-utils state=present
    - name: setup docker stable repository
      yum_repository:
        name: docker-ce
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    