---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: install yum-utils
      yum: name=yum-utils state=present
    - name: setup docker stable repository
      yum_repository:
        name: docker-ce
        description: setup docker-ce repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker-ce
      yum: name=docker-ce state=present
    - name: start docker service
      systemd: state=started name=docker