---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: install yum-utils
      yum: name=yum-utils state=present
    - name: add repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: refresh cache 
      command: yum makecache fast
    - name: install docker-ce
      yum: name=docker-ce state=present update_cache=yes
    - name: start docker service
      systemd: state=started name=docker
    - name: get docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: u+rwx
