---
- name: Install golang
  hosts: all
  become: yes
  vars:
    golang_version: 1.7
    golang_os: linux
    golang_arch: amd64
    ansible_ssh_user: centos
    golang_path: "/home/{{ansible_ssh_user}}/golang"
  tasks:
    - name: Download Go
      get_url: 
        url: "https://storage.googleapis.com/golang/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz" 
        dest: "/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"

    - name: Extract and install Go
      unarchive: 
        src: "/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
        dest: /usr/local/
        copy: no

    - name: Symlink Go into /usr/local/bin
      file: src="/usr/local/go/bin/{{ item }}" dest="/usr/local/bin/{{ item }}" state=link
      with_items:
        - go
        - godoc
        - gofmt
    - name: install git 
      yum: name=git state=present
    - name: make directory
      file: path="{{golang_path}}/src/github.com/hyperledger" state=directory
    - name: git clone the resository
      command: git clone ssh://halminhu@gerrit.hyperledger.org:29418/fabric && scp -p -P 29418 halminhu@gerrit.hyperledger.org:hooks/commit-msg fabric/.git/hooks/