# Prepare environment for hyperledger
---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: install yum-utils
      yum: name=yum-utils state=present
    - name: install epel gpg key
      command: rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    - name: Add epel repository
      yum: name=epel-release state=present
    - name: add docker ce repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: refresh yum cache 
      command: yum makecache fast
    
    - name: install docker-ce
      yum: name=docker-ce state=present update_cache=yes
    - name: start docker service
      systemd: state=started name=docker
    #- name: get docker-compose
    #  get_url:
    #    url: https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64
    #    dest: /usr/local/bin/docker-compose
    #    mode: u+rwx
     #   owner: centos
    - name: install gcc for pip modules
      yum: name=gcc state=present
    - name: install pip
      yum: name=python-pip state=present
    - name: install python dev and libssl dev
      yum: name=python-devel,openssl-devel state=present
    - name: update pip
      command: pip install --upgrade pip
    - name: install pip modules
      command: pip install behave nose docker-compose
    - name: install other pip modules
      command: pip install -I flask==0.10.1 python-dateutil==2.2 pytz==2014.3 pyyaml==3.10 couchdb==1.0 flask-cors==2.0.1 requests==2.4.3 pyOpenSSL==16.2.0 pysha3==1.0b1 grpcio==1.0.4
