---
- name: Install nodejs
  hosts: all
 # become: yes
  vars:
    golang_version: 1.7
    golang_os: linux
    golang_arch: amd64
    ansible_ssh_user: ubuntu
    golang_path: "/home/{{ansible_ssh_user}}/golang"
  tasks:
#- name: install git 
    #  yum: name=git state=present
    - name: make directory to download sourcecode
      file: path="{{golang_path}}/src/github.com/hyperledger" state=directory
    
    - name: git source code
      git: 
        repo: https://github.com/hyperledger/fabric.git
        dest: "{{golang_path}}/src/github.com/hyperledger"

    # - name: make directory
    #   file: path="/home/{{ansible_ssh_user}}/test" state=directory
    # - name: download the test script
    #   get_url:
    #     url: "https://raw.githubusercontent.com/hyperledger/fabric/master/examples/sfhackfest/sfhackfest.tar.gz"
    #     dest: "/home/{{ansible_ssh_user}}/test/sfhackfest.tar.gz"
    # - name: Extract the tar
    #   unarchive: 
    #     src: "/home/{{ansible_ssh_user}}/test/sfhackfest.tar.gz"
    #     dest: "/home/{{ansible_ssh_user}}/test"
    #     copy: no
    # Not clone the source code at this time
    #- name: git clone the resository
    #  command: git clone ssh://halminhu@gerrit.hyperledger.org:29418/fabric && scp -p -P 29418 halminhu@gerrit.hyperledger.org:hooks/commit-msg fabric/.git/hooks/
  