---
- name: Install golang
  hosts: all
 # become: yes
  vars:
    golang_version: 1.7
    golang_os: linux
    golang_arch: amd64
    ansible_ssh_user: centos
    golang_path: "/home/{{ansible_ssh_user}}/golang"
  tasks:
    - name: Download Go
      get_url: 
        url: "https://storage.googleapis.com/golang/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz" 
        dest: "/home/{{ansible_ssh_user}}/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"

    - name: Extract and install Go
      unarchive: 
        src: "/home/{{ansible_ssh_user}}/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
        dest: "/usr/local/"
        copy: no
      become: yes

    - name: Symlink Go into /usr/local/bin
      become: yes
      file: src="/usr/local/go/bin/{{ item }}" dest="/usr/local/bin/{{ item }}" state=link 
      with_items:
       - go 
       - godoc
       - gofmt

    #- name: install git 
    #  yum: name=git state=present
    - name: make directory
      file: path="/home/{{ansible_ssh_user}}/test" state=directory
    - name: download the test script
      get_url:
        url: "https://raw.githubusercontent.com/hyperledger/fabric/master/examples/sfhackfest/sfhackfest.tar.gz"
        dest: "/home/{{ansible_ssh_user}}/test/sfhackfest.tar.gz"
    - name: Extract the tar
      unarchive: 
        src: "/home/{{ansible_ssh_user}}/test/sfhackfest.tar.gz"
        dest: "/home/{{ansible_ssh_user}}/test"
        copy: no
    # Not clone the source code at this time
    #- name: git clone the resository
    #  command: git clone ssh://halminhu@gerrit.hyperledger.org:29418/fabric && scp -p -P 29418 halminhu@gerrit.hyperledger.org:hooks/commit-msg fabric/.git/hooks/
    - name: install gcc-c++ for node.js
      yum: name=gcc-c++ sate=present
      become: yes
    - name: install make for node.js
      yum: name=make sate=present
      become: yes
    - name: install nvm
      command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    - name: load nvm
      command: export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    - name: install node.js
      command: nvm install v6.9.5
