# Prepare environment for hyperledger
---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    
    - name: remove default docker
      apt: name={{item}} state=absent
      with_items:
          - docker
          - docker-engine
    - name: install pre-requisite package for docker-ce
      apt: name={{item}} state=present
      with_items:
          - apt-transport-https 
          - ca-certificates 
          - curl 
          - software-properties-common
    - name: Add Docker’s official GPG key
      apt_key: url="https://download.docker.com/linux/ubuntu/gpg" state=present
    - name: add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present
    - name: install docker-ce
      apt: name=docker-ce state=present update_cache=yes